ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.byron.RoutingKt.configureRouting

hotelier:
  suppliers:
    maxRetries: 3
    enabled:
      - ACME
      - PAPERFLIES
      - PATAGONIA
